project:
  type: website
  output-dir: docs
  preview: 
    port: 1200
    browser: true
    
execute:
  freeze: auto
  message: false
  warning: false

website:
  title: "Making it Count: Ecosystem Accounting in the Main Hawaiian Islands"
  navbar:
    left:
      - href: index.qmd
        text: Dashboard
      - href: data-processing.qmd
        text: Data Processing
    back-to-top-navigation: true
    
format:
  html:
    theme: litera
      # - styles.scss
    toc: true
    toc-location: left
    toc-title: "Data Analysis Workflow:"
    fontsize: 12pt
    page-layout: full
    margin-header: |
      <br><center>
      ![](/www/logos/uhm-logo.png) 
      <br><br>
      ![](/www/logos/pew-logo.png){width="130"} 
      <br><br>
      ![](/www/logos/sea-grant-logo.png){height="150"}
      <br><br>
      ![](/www/logos/pi-casc-logo.png){height="150"}
      <br><br></center>